[package]
name = "hawk-t1-checklist"
version = "1.0.0"
description = "Hawk T1 Flight Checklist"
authors = ["Jay"]
edition = "2021"

[lib]
name = "hawk_t1_checklist_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
